name: agriconnect
description: Precision farming application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.3
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.15.8
  equatable: ^2.0.5
  firebase_auth: ^4.17.8
  firebase_core: ^2.27.0
  firebase_database: ^10.4.9
  firebase_messaging: ^14.7.19
  fl_chart: ^0.66.2
  flutter_bloc: ^8.1.4
  font_awesome_flutter: ^10.7.0
  flutter_form_builder: ^9.1.0

  formz: ^0.7.0
  getwidget: ^4.0.0
  geolocator:
  google_sign_in: ^6.2.1
  http: ^1.1.2
  intl: ^0.18.0
  page_transition: ^2.1.0
  pedantic: ^1.11.1
  form_builder_validators:
  provider: ^6.1.1
#  page_view_indicator: ^2.0.4
  page_view_dot_indicator: ^2.3.0
#  flutter_clean_calendar: ^1.1.0
  flutter_neat_and_clean_calendar: ^0.3.14+32
  image_picker: ^1.0.7
  image_cropper: ^5.0.1
#  tflite_flutter: ^0.10.4
  tflite_flutter_plus: ^0.0.1
  tflite_flutter_helper_plus: ^0.0.2
#  tflite_flutter_helper: ^0.3.1
  logger: ^2.1.0
  geocoding: ^3.0.0
  weather: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0  # Add the version constraint

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/images/agri_connect_logo.png"
  image_path_ios: "assets/images/agri_connect_logo.png"
  adaptive_icon_background: "#FFFFFF"
#  adaptive_icon_foreground: "assets/images/agri_connect_logo_foreground.png"
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/model.tflite
    - assets/dict.txt

  fonts:
    - family: WeatherIcons
      fonts:
        - asset: fonts/weathericons-regular-webfont.ttf
