// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPKnOU-Ph7DTzoezCfxO8NEMRLhAuLpVw',
    appId: '1:676696649244:web:101fb16e71b18d16a439d9',
    messagingSenderId: '676696649244',
    projectId: 'agriconnect-e57ff',
    authDomain: 'agriconnect-e57ff.firebaseapp.com',
    storageBucket: 'agriconnect-e57ff.appspot.com',
    measurementId: 'G-GRL5HPTG8Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIvCS_uo_uEiDfMTTs7ZU88bJoDeqz3y4',
    appId: '1:676696649244:android:0f3b71fc5fb74d47a439d9',
    messagingSenderId: '676696649244',
    projectId: 'agriconnect-e57ff',
    storageBucket: 'agriconnect-e57ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlqFIRFNwGMrVRLaXadv6IVDnSDGi4YvI',
    appId: '1:676696649244:ios:69238414f87daef1a439d9',
    messagingSenderId: '676696649244',
    projectId: 'agriconnect-e57ff',
    storageBucket: 'agriconnect-e57ff.appspot.com',
    iosBundleId: 'com.example.agriconnect',
  );
}
